### PR TITLE
Fix TUI error when no scripts in readme with simple error

### LINKED ISSUE #109: TUI fails when README.md has no scripts
When README.md has no scripts, the tui is subject to error when pressing enter, and will show the current entry as `1/0`. 

I think in this case, it's easiest to error and close the program. Alternatively, we could show "No Scripts" in the TUI. The latter might be better if we intend to implement a "refresh" functionality at some point.

### PR DESCRIPTION
**Pull request by mxsdev**
Fixes #109 

This takes the simplest solution, which just prints an error message to prevent the TUI from running.

### CODE REVIEW

File: internal/cmd/tui.go [hunk 1]
```diff
@@ -196,6 +197,10 @@ func tuiCmd() *cobra.Command {
 				return err
 			}
 
+			if len(blocks) == 0 {
+				return errors.New("no scripts in README.md")
```
Comment (adambabik) [inline internal/cmd/tui.go:201]: As a file might have a different name, let's do this:

```suggestion
				return errors.Errorf("no scripts in %s", fFileName)
```
