### PR TITLE
Fix .env which broke as part of moving cmds to the project service

### LINKED ISSUE #492: .env loading seems broken in CLI
Running `runme run hello1` with following files will not print "SOMETHING=this" as expected.

`.env`:
```
SOMETHING=this
```

`README.md`:
```
---
shell: bash
---

\`\`\`shell { name=hello1 }
echo SOMETHING=[${SOMETHING}]
\`\`\`
```

### PR DESCRIPTION
**Pull request by sourishkrout**
Please see #492 for details.

Before vs after:
```
❯ runme run hello1
SOMETHING1=[]
❯ ./runme run hello1
SOMETHING1=[this]
```

Fixes #492.

### CODE REVIEW

**Comment by sourishkrout** [comment]
@adambabik, please lemme know if this fix works for you. Please ignore the code coverage, it's low due to integration vs unit test (not in coverage report).

File: internal/runner/client/client_local.go [hunk 1]
```diff
@@ -95,7 +99,6 @@ func (r *LocalRunner) newExecutable(task project.Task) (runner.Executable, error
 		Logger:  r.logger,
 	}
 
-	// TODO(adamb): what about `r.envs`?
```
Comment (sourishkrout) [inline internal/runner/client/client_local.go:98]: @adambabik sounded like you had a hunch here

**Comment by sourishkrout** [comment]
@adambabik, please do a retro-review. Going through a review with @pastuxso right now so we can ship a fix quickly.

**Review by pastuxso — APPROVED** [review]

**Comment by adambabik** [comment]
@sourishkrout I think it's ok. The way the environment variables are handled in `internal/runner/client` is a bit unclear, but in the end all env go to a session which is passed to the runner via `ExecutableConfig` and from there the env are eventually taken.

I will send a follow up PR with clean up.
